"""empty message

Revision ID: b1454a538834
Revises: 
Create Date: 2017-12-14 00:12:36.947075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1454a538834'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('likes_ibfk_4', 'likes', type_='foreignkey')
    op.drop_column('likes', 'photo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('photo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('likes_ibfk_4', 'likes', 'photos', ['photo_id'], ['photo_id'])
    # ### end Alembic commands ###
